# This file contains all available configuration options
# with their default values.

# options for analysis running
run:
  # include test files or not, default is true
  tests: true
  timeout: 5m

  # which dirs to skip: issues from them won't be reported;
  # can use regexp here: generated.*, regexp is applied on full path;
  # default value is empty list, but default dirs are skipped independently
  # from this option's value (see skip-dirs-use-default).
  # "/" will be replaced by current OS file path separator to properly work
  # on Windows.
  skip-dirs:
    - pkg/kubernetes/fabric
    - testing/mocks

  # default is true. Enables skipping of directories:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true

  # Allow multiple parallel golangci-lint instances running.
  # If false (default) - golangci-lint acquires file lock on start.
  allow-parallel-runners: false

#issue:
#  exclude-use-default: false

linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - unused
    - varcheck
    - goimports
    - typecheck
    - errorlint
    - gofmt
    - misspell
    - nestif
    - sqlclosecheck
    - gosec
  disable-all: true

#em, not sure it's needed for every lint though... I'll check it later :)
linters-settings:
  gosimple:
    go: "1.16"
  staticcheck:
    go: "1.16"
  unused:
    go: "1.16"


issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA1019:"
    # Exclude some linters from running on tests files.
#    - path: \.go
#      linters:
#        - typecheck
