version: "3"

services:
  queue:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbit-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: f6fAjy5yes
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
  mysql:
    image: mysql:8.0.21
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foreman
      MYSQL_USER: foreman
      MYSQL_PASSWORD: foreman
    ports:
      - 3306:3306
  postgres:
    image: postgres
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: foreman
      POSTGRES_USER: foreman
      POSTGRES_DB: foreman
    restart: always
    ports:
      - 5432:5432

volumes:
  mysql-data: ~
  pgsql-data: ~
  rabbit-data: ~
