version: "3"

services:
  queue:
    image: rabbitmq:3.7.7-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 2000MiB
      RABBITMQ_ERLANG_COOKIE: f6fAjy5yes
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
  db:
    image: mysql:8.0.21
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: watcher
      MYSQL_USER: watcher
      MYSQL_PASSWORD: watcher
    ports:
      - 3306:3306

volumes:
  db-data: ~
